resources:
- ../../base

configMapGenerator:
- name: web-server-config
  files:
  - config.properties=../../../conf/config-prod.properties

images:
- name: yscraper-web-server
  newName: ghcr.io/flodia/rust-yscraper
  newTag: latest
- name: yscraper-liquibase
  newName: ghcr.io/flodia/rust-yscraper-liquibase
  newTag: latest
