apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yscraper

resources:
- ../../base

configMapGenerator:
- name: web-server-config
  files:
  - config.properties=../../../conf/config-prod.properties

images:
- name: yscraper-web-server
  newName: ghcr.io/homelab1025/rust-yscraper
  newTag: latest
- name: yscraper-liquibase
  newName: ghcr.io/homelab1025/rust-yscraper-liquibase
  newTag: latest
