# HTTP server port (can also be set as server.port)
port=3000
#db_url=postgres://postgres:postgres@localhost:5432/yscraper
db_host=localhost
db_user=postgres
db_password=postgres
dp_port=5432
db_name=yscraper