/* tslint:disable */
/* eslint-disable */
/**
 * web_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiError {
    'code': ApiErrorCode;
    'msg': string;
}



export const ApiErrorCode = {
    DatabaseError: 'DatabaseError',
    BadRequest: 'BadRequest',
    SchedulingError: 'SchedulingError',
    NotFound: 'NotFound'
} as const;

export type ApiErrorCode = typeof ApiErrorCode[keyof typeof ApiErrorCode];


export interface CommentDto {
    'date': string;
    'id': number;
    'state': CommentState;
    'subcomment_count': number;
    'text': string;
    'url_id': number;
    'user': string;
}



export const CommentState = {
    New: 'NEW',
    Picked: 'PICKED',
    Discarded: 'DISCARDED'
} as const;

export type CommentState = typeof CommentState[keyof typeof CommentState];


export interface CommentsPage {
    'items': Array<CommentDto>;
    'total': number;
}
export interface LinkDto {
    'date_added': string;
    'id': number;
    'picked_comment_count': number;
    'total_comment_count': number;
    'url': string;
}
export interface PingResponse {
    'msg': string;
}
export interface ScrapeRequest {
    /**
     * Number of days to keep refreshing comments (default: 7)
     */
    'days_limit'?: number | null;
    /**
     * Frequency in hours between refreshes (default: 24)
     */
    'frequency_hours'?: number | null;
    'item_id': number;
}
export interface ScrapeResponse {
    'state': ScrapeState;
}



export const ScrapeState = {
    Scheduled: 'Scheduled',
    AlreadyScheduled: 'AlreadyScheduled'
} as const;

export type ScrapeState = typeof ScrapeState[keyof typeof ScrapeState];



export const SortBy = {
    Date: 'date',
    SubcommentCount: 'subcomment_count'
} as const;

export type SortBy = typeof SortBy[keyof typeof SortBy];



export const SortOrder = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type SortOrder = typeof SortOrder[keyof typeof SortOrder];


export interface UpdateStateRequest {
    'state': CommentState;
}



/**
 * CrateApiCommentsApi - axios parameter creator
 */
export const CrateApiCommentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List comments with pagination
         * @param {number} urlId 
         * @param {number} [offset] 
         * @param {number} [count] 
         * @param {CommentState} [state] 
         * @param {SortBy} [sortBy] 
         * @param {SortOrder} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listComments: async (urlId: number, offset?: number, count?: number, state?: CommentState, sortBy?: SortBy, sortOrder?: SortOrder, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'urlId' is not null or undefined
            assertParamExists('listComments', 'urlId', urlId)
            const localVarPath = `/comments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (urlId !== undefined) {
                localVarQueryParameter['url_id'] = urlId;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update comment state
         * @param {number} id Comment ID
         * @param {UpdateStateRequest} updateStateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCommentState: async (id: number, updateStateRequest: UpdateStateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCommentState', 'id', id)
            // verify required parameter 'updateStateRequest' is not null or undefined
            assertParamExists('updateCommentState', 'updateStateRequest', updateStateRequest)
            const localVarPath = `/comments/{id}/state`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateStateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CrateApiCommentsApi - functional programming interface
 */
export const CrateApiCommentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CrateApiCommentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List comments with pagination
         * @param {number} urlId 
         * @param {number} [offset] 
         * @param {number} [count] 
         * @param {CommentState} [state] 
         * @param {SortBy} [sortBy] 
         * @param {SortOrder} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listComments(urlId: number, offset?: number, count?: number, state?: CommentState, sortBy?: SortBy, sortOrder?: SortOrder, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommentsPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listComments(urlId, offset, count, state, sortBy, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrateApiCommentsApi.listComments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update comment state
         * @param {number} id Comment ID
         * @param {UpdateStateRequest} updateStateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCommentState(id: number, updateStateRequest: UpdateStateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCommentState(id, updateStateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrateApiCommentsApi.updateCommentState']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CrateApiCommentsApi - factory interface
 */
export const CrateApiCommentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CrateApiCommentsApiFp(configuration)
    return {
        /**
         * 
         * @summary List comments with pagination
         * @param {number} urlId 
         * @param {number} [offset] 
         * @param {number} [count] 
         * @param {CommentState} [state] 
         * @param {SortBy} [sortBy] 
         * @param {SortOrder} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listComments(urlId: number, offset?: number, count?: number, state?: CommentState, sortBy?: SortBy, sortOrder?: SortOrder, options?: RawAxiosRequestConfig): AxiosPromise<CommentsPage> {
            return localVarFp.listComments(urlId, offset, count, state, sortBy, sortOrder, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update comment state
         * @param {number} id Comment ID
         * @param {UpdateStateRequest} updateStateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCommentState(id: number, updateStateRequest: UpdateStateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateCommentState(id, updateStateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CrateApiCommentsApi - object-oriented interface
 */
export class CrateApiCommentsApi extends BaseAPI {
    /**
     * 
     * @summary List comments with pagination
     * @param {number} urlId 
     * @param {number} [offset] 
     * @param {number} [count] 
     * @param {CommentState} [state] 
     * @param {SortBy} [sortBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listComments(urlId: number, offset?: number, count?: number, state?: CommentState, sortBy?: SortBy, sortOrder?: SortOrder, options?: RawAxiosRequestConfig) {
        return CrateApiCommentsApiFp(this.configuration).listComments(urlId, offset, count, state, sortBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update comment state
     * @param {number} id Comment ID
     * @param {UpdateStateRequest} updateStateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCommentState(id: number, updateStateRequest: UpdateStateRequest, options?: RawAxiosRequestConfig) {
        return CrateApiCommentsApiFp(this.configuration).updateCommentState(id, updateStateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CrateApiLinksApi - axios parameter creator
 */
export const CrateApiLinksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id Link ID to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLink: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteLink', 'id', id)
            const localVarPath = `/links/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve all links with their item IDs and added date.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLinks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/links`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Triggers scraping and inserts results into the database. Trigger a scrape task for a specific Hacker News item
         * @param {ScrapeRequest} scrapeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scrapeLink: async (scrapeRequest: ScrapeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'scrapeRequest' is not null or undefined
            assertParamExists('scrapeLink', 'scrapeRequest', scrapeRequest)
            const localVarPath = `/scrape`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(scrapeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CrateApiLinksApi - functional programming interface
 */
export const CrateApiLinksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CrateApiLinksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id Link ID to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLink(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLink(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrateApiLinksApi.deleteLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve all links with their item IDs and added date.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listLinks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LinkDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listLinks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrateApiLinksApi.listLinks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Triggers scraping and inserts results into the database. Trigger a scrape task for a specific Hacker News item
         * @param {ScrapeRequest} scrapeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async scrapeLink(scrapeRequest: ScrapeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ScrapeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.scrapeLink(scrapeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrateApiLinksApi.scrapeLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CrateApiLinksApi - factory interface
 */
export const CrateApiLinksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CrateApiLinksApiFp(configuration)
    return {
        /**
         * 
         * @param {number} id Link ID to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLink(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteLink(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve all links with their item IDs and added date.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLinks(options?: RawAxiosRequestConfig): AxiosPromise<Array<LinkDto>> {
            return localVarFp.listLinks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Triggers scraping and inserts results into the database. Trigger a scrape task for a specific Hacker News item
         * @param {ScrapeRequest} scrapeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scrapeLink(scrapeRequest: ScrapeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ScrapeResponse> {
            return localVarFp.scrapeLink(scrapeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CrateApiLinksApi - object-oriented interface
 */
export class CrateApiLinksApi extends BaseAPI {
    /**
     * 
     * @param {number} id Link ID to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteLink(id: number, options?: RawAxiosRequestConfig) {
        return CrateApiLinksApiFp(this.configuration).deleteLink(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve all links with their item IDs and added date.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listLinks(options?: RawAxiosRequestConfig) {
        return CrateApiLinksApiFp(this.configuration).listLinks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Triggers scraping and inserts results into the database. Trigger a scrape task for a specific Hacker News item
     * @param {ScrapeRequest} scrapeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public scrapeLink(scrapeRequest: ScrapeRequest, options?: RawAxiosRequestConfig) {
        return CrateApiLinksApiFp(this.configuration).scrapeLink(scrapeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CrateApiPingApi - axios parameter creator
 */
export const CrateApiPingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health check handler: echoes back the provided `msg` with the current Unix timestamp
         * @param {string} [msg] Message to echo back
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ping: async (msg?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (msg !== undefined) {
                localVarQueryParameter['msg'] = msg;
            }

            localVarHeaderParameter['Accept'] = 'application/json,text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CrateApiPingApi - functional programming interface
 */
export const CrateApiPingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CrateApiPingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health check handler: echoes back the provided `msg` with the current Unix timestamp
         * @param {string} [msg] Message to echo back
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ping(msg?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ping(msg, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrateApiPingApi.ping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CrateApiPingApi - factory interface
 */
export const CrateApiPingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CrateApiPingApiFp(configuration)
    return {
        /**
         * 
         * @summary Health check handler: echoes back the provided `msg` with the current Unix timestamp
         * @param {string} [msg] Message to echo back
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ping(msg?: string, options?: RawAxiosRequestConfig): AxiosPromise<PingResponse> {
            return localVarFp.ping(msg, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CrateApiPingApi - object-oriented interface
 */
export class CrateApiPingApi extends BaseAPI {
    /**
     * 
     * @summary Health check handler: echoes back the provided `msg` with the current Unix timestamp
     * @param {string} [msg] Message to echo back
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ping(msg?: string, options?: RawAxiosRequestConfig) {
        return CrateApiPingApiFp(this.configuration).ping(msg, options).then((request) => request(this.axios, this.basePath));
    }
}



