name: Liquibase Docker Build

on:
  push:
    branches: ["main"]
    paths:
      - "db/**"
      - ".github/workflows/liquibase-build.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "db/**"
      - ".github/workflows/liquibase-build.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-liquibase

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: db
          file: db/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
